server:
  env: "dev"
  host: ""
  port: 8030

redis:
  address: "localhost:6379"
  password: ""
  db: 0

database:
  driver: ""
  host: "localhost"
  port: "27017"
  user: "root"
  password: "examplepass001"
  db_name: "simplepos"

auth-token:
  duration: 3600
  secretkey: "anysecret"
